### ISSUE TITLE
Won't play Transcoded Resolutions on Kodi 19 Matrix

### ISSUE THREAD

**Issue by ashipaek0** [cguZZman/plugin.googledrive#253]
On Kodi 19 the add-on plays only the max resolution of video files

It doesn't respect the settings to choose a lower resolution.

Also when you navigate to the drive directly through the add-on and uses the 'play choosing stream format' option, it does not provide the alternative Transcoded resolutions.

It brings up the 'loading streams format.....'  and skips to just play the max file resolution directly.

This all worked just fine in 18.9.

**Comment by Dhionatha** [comment]
The same thing happens to me

**Comment by jmiskinis** [comment]
Can confirm there's no way to select transcoded resolutions.

**Comment by cguZZman** [comment]
Will work on this one soon.

**Comment by ashipaek0** [comment]
> Will work on this one soon.

Hello Sir,

Not to intrude but I was wondering if there's any update on this issue.

Thanks for your awesome work

**Comment by cguZZman** [comment]
Fixed in version 1.4.11. Available now in my repo.

**Comment by jmiskinis** [comment]
New version seems to produce a dependency error:

```
2021-07-30 00:31:57.503 T:22724   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.googledrive'.
2021-07-30 00:31:57.503 T:22724   ERROR <general>: Exception in thread 
2021-07-30 00:31:57.503 T:22724   ERROR <general>: service-export
2021-07-30 00:31:57.503 T:22724   ERROR <general>: :
                                                   
2021-07-30 00:31:57.503 T:22724   ERROR <general>: Traceback (most recent call last):
                                                   
2021-07-30 00:31:57.503 T:22724   ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-07-30 00:31:57.504 T:22724   ERROR <general>:     
2021-07-30 00:31:57.504 T:22724   ERROR <general>: self.run()
2021-07-30 00:31:57.504 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.504 T:22724   ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 870, in run
                                                   
2021-07-30 00:31:57.506 T:22724   ERROR <general>:     
2021-07-30 00:31:57.506 T:22724   ERROR <general>: self._target(*self._args, **self._kwargs)
2021-07-30 00:31:57.506 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.506 T:22724   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/export.py", line 109, in start
                                                   
2021-07-30 00:31:57.507 T:22724   ERROR <general>:     
2021-07-30 00:31:57.507 T:22724   ERROR <general>: Logger.notice('Service stopped.')
2021-07-30 00:31:57.507 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.507 T:22724   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/logger.py", line 29, in notice
                                                   
2021-07-30 00:31:57.508 T:22724   ERROR <general>:     
2021-07-30 00:31:57.508 T:22724   ERROR <general>: KodiUtils.log(msg, KodiUtils.LOGNOTICE)
2021-07-30 00:31:57.508 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.508 T:22724   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 221, in log
                                                   
2021-07-30 00:31:57.509 T:22724   ERROR <general>:     
2021-07-30 00:31:57.509 T:22724   ERROR <general>: xbmc.log(u'[%s][%s-%s]: %s' % (KodiUtils.get_addon_info('id'), threading.current_thread().name,threading.current_thread().ident, Utils.str(msg)), level)
2021-07-30 00:31:57.509 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.509 T:22724   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 176, in get_addon_info
                                                   
2021-07-30 00:31:57.509 T:22724   ERROR <general>:     
2021-07-30 00:31:57.509 T:22724   ERROR <general>: addon = KodiUtils.get_addon(addonid)
2021-07-30 00:31:57.509 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.509 T:22724   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 41, in get_addon
                                                   
2021-07-30 00:31:57.510 T:22724   ERROR <general>:     
2021-07-30 00:31:57.510 T:22724   ERROR <general>: return xbmcaddon.Addon()
2021-07-30 00:31:57.510 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.510 T:22724   ERROR <general>: RuntimeError
2021-07-30 00:31:57.510 T:22724   ERROR <general>: : 
2021-07-30 00:31:57.510 T:22724   ERROR <general>: Unknown addon id 'plugin.googledrive'.
2021-07-30 00:31:57.510 T:22724   ERROR <general>: 
                                                   
2021-07-30 00:31:57.514 T:22725   ERROR <general>:     
2021-07-30 00:31:57.514 T:22725   ERROR <general>: self.run()
2021-07-30 00:31:57.514 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.514 T:22725   ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 870, in run
                                                   
2021-07-30 00:31:57.515 T:22725   ERROR <general>:     
2021-07-30 00:31:57.515 T:22725   ERROR <general>: self._target(*self._args, **self._kwargs)
2021-07-30 00:31:57.515 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.515 T:22725   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/player.py", line 58, in start
                                                   
2021-07-30 00:31:57.515 T:22725   ERROR <general>:     
2021-07-30 00:31:57.515 T:22725   ERROR <general>: Logger.notice('Service stopped.')
2021-07-30 00:31:57.515 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.515 T:22725   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/logger.py", line 29, in notice
                                                   
2021-07-30 00:31:57.516 T:22725   ERROR <general>:     
2021-07-30 00:31:57.516 T:22725   ERROR <general>: KodiUtils.log(msg, KodiUtils.LOGNOTICE)
2021-07-30 00:31:57.516 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.516 T:22725   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 221, in log
                                                   
2021-07-30 00:31:57.516 T:22725   ERROR <general>:     
2021-07-30 00:31:57.516 T:22725   ERROR <general>: xbmc.log(u'[%s][%s-%s]: %s' % (KodiUtils.get_addon_info('id'), threading.current_thread().name,threading.current_thread().ident, Utils.str(msg)), level)
2021-07-30 00:31:57.516 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.516 T:22725   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 176, in get_addon_info
                                                   
2021-07-30 00:31:57.517 T:22725   ERROR <general>:     
2021-07-30 00:31:57.517 T:22725   ERROR <general>: addon = KodiUtils.get_addon(addonid)
2021-07-30 00:31:57.517 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.517 T:22725   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 41, in get_addon
                                                   
2021-07-30 00:31:57.517 T:22725   ERROR <general>:     
2021-07-30 00:31:57.517 T:22725   ERROR <general>: return xbmcaddon.Addon()
2021-07-30 00:31:57.517 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.517 T:22725   ERROR <general>: RuntimeError
2021-07-30 00:31:57.517 T:22725   ERROR <general>: : 
2021-07-30 00:31:57.517 T:22725   ERROR <general>: Unknown addon id 'plugin.googledrive'.
2021-07-30 00:31:57.517 T:22725   ERROR <general>: 
                                                   
2021-07-30 00:31:57.624 T:22533   ERROR <general>: CAddonInstallJob[plugin.googledrive]: found dependency [script.module.clouddrive.common/1.3.9+matrix.2] doesn't meet minimum version [1.3.10]
2021-07-30 00:31:57.837 T:22719   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.googledrive'.
2021-07-30 00:31:57.850 T:22719   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Unknown addon id 'plugin.googledrive'.
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.googledrive/service.py", line 29, in <module>
                                                       ServiceUtil.run([DownloadService(GoogleDrive), SourceService(GoogleDrive),
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/utils.py", line 39, in run
                                                       service.stop()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/service/base.py", line 60, in stop
                                                       Logger.notice('Service stopped')
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/logger.py", line 29, in notice
                                                       KodiUtils.log(msg, KodiUtils.LOGNOTICE)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 221, in log
                                                       xbmc.log(u'[%s][%s-%s]: %s' % (KodiUtils.get_addon_info('id'), threading.current_thread().name,threading.current_thread().ident, Utils.str(msg)), level)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 176, in get_addon_info
                                                       addon = KodiUtils.get_addon(addonid)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/utils.py", line 41, in get_addon
                                                       return xbmcaddon.Addon()
                                                   RuntimeError: Unknown addon id 'plugin.googledrive'.
                                                   -->End of Python script error report<--
                                                   
2021-07-30 00:31:57.851 T:22719    INFO <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.googledrive/service.py): waiting on thread 499478723920
2021-07-30 00:32:02.501 T:22537   ERROR <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.googledrive/service.py): script didn't stop in 5 seconds - let's kill it
2021-07-30 00:32:02.504 T:22436 WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-07-30 00:32:02.763 T:22436 WARNING <general>: Skipped 3 duplicate messages..
2021-07-30 00:32:02.763 T:22436 WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-07-30 00:32:02.773 T:22436   ERROR <general>: Skipped 1 duplicate messages..
2021-07-30 00:32:02.773 T:22436   ERROR <general>: CGUIMediaWindow::GetDirectory(addons://repository.cguzzman/xbmc.addon.video) failed
2021-07-30 00:32:02.868 T:22719   ERROR <general>: Exception ignored in: 
2021-07-30 00:32:02.868 T:22719   ERROR <general>: <module 'threading' from '/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py'>
2021-07-30 00:32:02.868 T:22719   ERROR <general>: 
                                                   
2021-07-30 00:32:02.868 T:22719   ERROR <general>: Traceback (most recent call last):
                                                   
2021-07-30 00:32:02.868 T:22719   ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 1355, in _shutdown
                                                   
2021-07-30 00:32:02.869 T:22719   ERROR <general>:     
2021-07-30 00:32:02.870 T:22719   ERROR <general>: def _shutdown():
2021-07-30 00:32:02.870 T:22719   ERROR <general>: 
                                                   
2021-07-30 00:32:02.870 T:22719   ERROR <general>: SystemExit
2021-07-30 00:32:02.870 T:22719   ERROR <general>: : 
2021-07-30 00:32:02.870 T:22719   ERROR <general>: 
2021-07-30 00:32:02.870 T:22719   ERROR <general>: 
                                                   
2021-07-30 00:32:02.988 T:22719    INFO <general>: Python interpreter interrupted by user
2021-07-30 00:32:18.784 T:22537   ERROR <general>: CAddonInstallJob[plugin.googledrive]: found dependency [script.module.clouddrive.common/1.3.9+matrix.2] doesn't meet minimum version [1.3.10]
2021-07-30 00:32:23.376 T:22436    INFO <general>: Skipped 1 duplicate messages..
2021-07-30 00:32:23.376 T:22436    INFO <general>: CWinSystemAndroid::DestroyWindow
2021-07-30 00:33:27.045 T:22436    INFO <general>: CAndroidUtils: SetNativeResolution: -1: 2560x1600 2560x1600@60.000004
2021-07-30 00:33:27.047 T:22436    INFO <general>: GL_VENDOR = Qualcomm
2021-07-30 00:33:27.047 T:22436    INFO <general>: GL_RENDERER = Adreno (TM) 540
2021-07-30 00:33:27.047 T:22436    INFO <general>: GL_VERSION = OpenGL ES 3.2 V@415.0 (GIT@f3ac570, I0807496fd3, 1599233713) (Date:09/04/20)
2021-07-30 00:33:27.047 T:22436    INFO <general>: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20
2021-07-30 00:33:27.047 T:22436    INFO <general>: GL_EXTENSIONS = GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather 
2021-07-30 00:33:30.263 T:23338   ERROR <general>: CAddonInstallJob[plugin.googledrive]: found dependency [script.module.clouddrive.common/1.3.9+matrix.2] doesn't meet minimum version [1.3.10]
2021-07-30 00:33:32.914 T:22436    INFO <general>: CWinSystemAndroid::DestroyWindow

```

**Comment by cguZZman** [comment]
post the entire log file. with debug

**Comment by jmiskinis** [comment]
Thanks for a quick reply!

https://pastebin.com/8xEnwLvm

**Comment by cguZZman** [comment]
that link does not work

**Comment by jmiskinis** [comment]
My bad, pastebin.com seems to delete my posts. Here you go: https://pastebin.pl/view/5d836ff7

**Comment by cguZZman** [comment]
there is no error or addon use in that log

**Comment by jmiskinis** [comment]
There's no use of add-on because it's not installed. I get the dependency error when I try to install the add-on from your repository. I believe it's line 1508 in the log I posted or am I wrong?:
`ERROR <general>: CAddonInstallJob[plugin.googledrive]: found dependency [script.module.clouddrive.common/1.3.9+matrix.2] doesn't meet minimum version [1.3.10]`

**Comment by jmiskinis** [comment]
Sorry for posting in the closed issue but can any of you (@ashipaek0, @Dhionatha) install the new (1.4.11) version?

**Comment by ashipaek0** [comment]
Yes. From the Devs repo

**Comment by ashipaek0** [comment]
> Sorry for posting in the closed issue but can any of you (@ashipaek0, @Dhionatha) install the new (1.4.11) version?

Yes from the Devs repo

**Comment by jmiskinis** [comment]
Thanks for the reply. I was able to install the plug-in after manually installing the clouddrive.common module.

**Comment by Axanderism** [comment]
I just upgraded to Matrix and my Drive version is stuck on 1.4. 10 and it doesn't work well at all. 

Where do I get the new version 1.4.11 from please?
