### ISSUE TITLE
Auto-Refreshed slideshow fails to play

### ISSUE THREAD

**Issue by StealthMuscles** [cguZZman/plugin.googledrive#85]
**Describe the bug**
When trying to play a Google Photos album with a few pictures in it as an "Auto-Refreshed slideshow", playback fails with an error which is displayed on the screen.

Unknown error:
'GoogleDrive' object has no attribute '_parameters'.
Please try again

**To Reproduce**
1. Context menu on a Google Photos album
2. Select "Auto-Refreshed slideshow"
3. Failure

Note, normal and Recursive slideshow playback options work correctly.

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/3679152/kodi.log)

```
2019-10-01 21:49:26.853 T:1477440224   DEBUG: [plugin.googledrive][MainThread-1477440224]: {'item_id': 'album-ABBNpCNcmopxrNh_BXQn9FeHjIEeF0yspNfktC95X_fQDJ8_sQuP4LVHX_VzQqX4oN3gMeDbP8Y5', 'driveid': '05201362687723676141', 'item_driveid': '05201362687723676141', 'action': '_slideshow', 'content_type': 'image'}
2019-10-01 21:49:26.857 T:1477440224   ERROR: [plugin.googledrive][MainThread-1477440224]: [plugin.googledrive] [1.2.12]/[1.2.8]
                                            
                                            Unknown error:
                                            'GoogleDrive' object has no attribute '_parameters'
                                            Please try again.
                                            
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 764, in route
                                                method(**arguments)
                                              File "/home/osmc/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 552, in _slideshow
                                                new_change_token = self.new_change_token_slideshow(change_token, driveid, item_driveid, item_id, path)
                                              File "/home/osmc/.kodi/addons/plugin.googledrive/addon.py", line 57, in new_change_token_slideshow
                                                response = self._provider.get('/changes/startPageToken', parameters = self._provider._parameters)
                                            AttributeError: 'GoogleDrive' object has no attribute '_parameters'
                                            
                                            
                                            show_error_dialog: True
```

**Comment by cguZZman** [comment]
You are using and old version of the plugin. Please update it and try again.

**Comment by StealthMuscles** [comment]
It's the same in version 1.3.  I don't see how this ever could have worked for photos, as you're trying to call a Drive endpoint: 

`def new_change_token_slideshow(self, change_token, driveid, item_driveid=None, item_id=None, path=None):
        self._provider.configure(self._account_manager, driveid)
        if not change_token:
            response = self._provider.get('/changes/startPageToken', parameters = self._provider._parameters)
            self._change_token = Utils.get_safe_value(response, 'startPageToken')
            change_token = 1
        else:`
<snip>

**Comment by cguZZman** [comment]
Your debug log file shows you are using 1.2.12:
`2019-10-01 20:51:04.089 T:1430201056  NOTICE: ADDON: plugin.googledrive v1.2.12 installed`

And yea, not that you mention it, auto-refreshed slideshow is not implemented for google photos album. It works only for photos stored in your drive.

I'll mark this as a possible enhancement.

**Comment by Gametyrant** [comment]
Letting the the google slideshow automatically update itself would be a HUGE benefit to the way we have implemented your plugin. Maybe this has been implemented already but I am hoping that I can just update my google folders with various .jpgs and it will auto update my live slideshows. 

We are using raspberry Pi's to hook up to individual monitors in our gaming center and this would allow me to change the pictures on the fly without having to update each monitor individually. Really appreciate you work!

**Comment by cguZZman** [comment]
That's the idea with the auto-refreshed slideshow, but works only with folders inside of your drive, not in Google Photos albums.
